title: Snipy's Blog
name: Snipy's Blog
email: sylvain.julmy@gmail.com
description: Blogging about Chess, Computer Science and more !
url: "http://snipyjulmy.github.io"
baseurl: ""
twitter_username: SylvainJulmy
github_username:  SnipyJulmy

paginate: 10

#theme: minima
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']